apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: easyshop-tls
  namespace: easyshop
spec:
  dnsNames:
    - easyshop.letsdeployit.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-issuer
  secretName: easyshop-tls
  usages:
    - digital signature
    - key encipherment 